version: '3.1'

services:
    tuneship-db: 
        env_file: docker/.env
        container_name: tuneship-db
        build:
            context: db
            dockerfile: Dockerfile
        ports:
            - 5435:5432
        restart: unless-stopped 
        volumes:
            - '/var/lib/postgresql/data'
            - ./data:/data
