"""empty message

Revision ID: 8b0dbd6c2b7d
Revises: 
Create Date: 2018-10-26 14:46:18.973968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0dbd6c2b7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_notes'), 'data', ['notes'], unique=False)
    op.create_table('tunes_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('thumb_url', sa.String(length=128), nullable=True),
    sa.Column('media_url', sa.String(length=256), nullable=True),
    sa.Column('iframe_string', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iframe_string'),
    sa.UniqueConstraint('media_url')
    )
    op.create_index(op.f('ix_tunes_data_title'), 'tunes_data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tunes_data_title'), table_name='tunes_data')
    op.drop_table('tunes_data')
    op.drop_index(op.f('ix_data_notes'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
