"""empty message

Revision ID: 9c891c8a3c18
Revises: bde6cf836f8f
Create Date: 2018-10-26 14:09:12.649383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c891c8a3c18'
down_revision = 'bde6cf836f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunes_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('thumb_url', sa.String(length=128), nullable=True),
    sa.Column('media_url', sa.String(length=256), nullable=True),
    sa.Column('iframe_string', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iframe_string'),
    sa.UniqueConstraint('media_url')
    )
    op.create_index(op.f('ix_tunes_data_title'), 'tunes_data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tunes_data_title'), table_name='tunes_data')
    op.drop_table('tunes_data')
    # ### end Alembic commands ###
