"""empty message

Revision ID: cb18fc926c3c
Revises: 
Create Date: 2017-11-26 19:45:08.226371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb18fc926c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunes_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('thumb_url', sa.String(length=128), nullable=True),
    sa.Column('media_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tunes_data_media_url'), 'tunes_data', ['media_url'], unique=True)
    op.create_index(op.f('ix_tunes_data_thumb_url'), 'tunes_data', ['thumb_url'], unique=False)
    op.create_index(op.f('ix_tunes_data_title'), 'tunes_data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tunes_data_title'), table_name='tunes_data')
    op.drop_index(op.f('ix_tunes_data_thumb_url'), table_name='tunes_data')
    op.drop_index(op.f('ix_tunes_data_media_url'), table_name='tunes_data')
    op.drop_table('tunes_data')
    # ### end Alembic commands ###
