"""empty message

Revision ID: fa82dacc1f83
Revises: df5714f3129d
Create Date: 2017-11-26 22:19:33.117263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa82dacc1f83'
down_revision = 'df5714f3129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tunes_data_iframe_string', table_name='tunes_data')
    op.drop_index('ix_tunes_data_media_url', table_name='tunes_data')
    op.drop_index('ix_tunes_data_thumb_url', table_name='tunes_data')
    op.create_unique_constraint(None, 'tunes_data', ['media_url'])
    op.create_unique_constraint(None, 'tunes_data', ['iframe_string'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tunes_data', type_='unique')
    op.drop_constraint(None, 'tunes_data', type_='unique')
    op.create_index('ix_tunes_data_thumb_url', 'tunes_data', ['thumb_url'], unique=False)
    op.create_index('ix_tunes_data_media_url', 'tunes_data', ['media_url'], unique=True)
    op.create_index('ix_tunes_data_iframe_string', 'tunes_data', ['iframe_string'], unique=True)
    # ### end Alembic commands ###
